In [3]:
#to import numpy 
import numpy as np

In [4]:
#numpy array shape
np1 = np.array([0,1,2,3,4,5,6,7,8,9])
print(np1)

[0 1 2 3 4 5 6 7 8 9]


In [5]:
#np1.shape means we can know how many elements in an numpy array has
print(np1.shape)

(10,)


In [6]:
#numpy arange function -> np.arange(start,stop, step)
#suppose we want to create an array which starts at 0 and ends before 10 , with a gap of 2. This means we want our array to include every second number starting from 0 upt to 10 .
np2 = np.arange(0,10,2)
print(np2)

[0 2 4 6 8]


In [7]:
#numpy zeros function -> np.zeroes(shape,dtype=float, order='C') 
np3 = np.zeros((3,4))
print(np3)

#to create a 3d array we can use 
np31 = np.zeros(shape=(2,3,4), dtype=float , order='F')
print(np31)

#two types of order 'C' and 'F'
#differnce is in C type elements are stored in memory row by row and last rightmost index change the fastest.efficent for accessing or modyfying rows at a time
#In 'F' type elements are stored in memory coloumn wise and first leftmost index changes the fastest.efficent for accessing or modyfying columns at a time
np32 = np.full((2,10),6)
print(np32)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]
[[6 6 6 6 6 6 6 6 6 6]
 [6 6 6 6 6 6 6 6 6 6]]


In [8]:
#convet python list to numpy array
my_list = [1,2,3,4,5]
np4 = np.array(my_list)
print(np4)

#accessing any item on the array 
print(np4[0])
print(np4[3])

[1 2 3 4 5]
1
4


In [9]:
#Slicing numpy arrays 
np5 = np.array([1,2,3,4,5,6,7,8,9])

#return 2,3,4,5
print(np5[1:5])

#return from something from the array
print(np5[2:])

#return negative slices 
print(np5[-3:-1])

#sicing with steps
print(np5[1:5:2])

[2 3 4 5]
[3 4 5 6 7 8 9]
[7 8]
[2 4]


In [10]:
#create 2D array 
np6 = np.array([
    [1,2,3,4,5,6], 
    [2,3,4,5,6,7]])
print(np6[1,2])

#slice a 2D array 
print(np6[0:1, 1:3])
#means list no. 0 upto list no. 1 then within that list ,from element no. 1 to 3


4
[[2 3]]


In [11]:
#Universal functions in Numpy 
np7  = np.array([1,2,3,4,5,6,7,8,9])
print(np7)

#sqrt
print(np.sqrt(np7))

#absolute value of function = makes absolute positive to any no.
print(np.absolute(np7))

#exponents
print(np.exp(np7))

#min and max
print(np.min(np7))
print(np.max(np7))

#sign negative or positive
print(np.sign(np7))

#trig sin cos log
print(np.cos(np7))
print(np.log(np7))
print(np.sin(np7))

[1 2 3 4 5 6 7 8 9]
[1.         1.41421356 1.73205081 2.         2.23606798 2.44948974
 2.64575131 2.82842712 3.        ]
[1 2 3 4 5 6 7 8 9]
[2.71828183e+00 7.38905610e+00 2.00855369e+01 5.45981500e+01
 1.48413159e+02 4.03428793e+02 1.09663316e+03 2.98095799e+03
 8.10308393e+03]
1
9
[1 1 1 1 1 1 1 1 1]
[ 0.54030231 -0.41614684 -0.9899925  -0.65364362  0.28366219  0.96017029
  0.75390225 -0.14550003 -0.91113026]
[0.         0.69314718 1.09861229 1.38629436 1.60943791 1.79175947
 1.94591015 2.07944154 2.19722458]
[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155
  0.6569866   0.98935825  0.41211849]


In [12]:

np8  = np.array([1,2,3,4,5,6,7,8,9])
print(np8)

'''#Copy vs View
#create a view
np9 = np8.view()

print(f'Original NP8 {np8}')
print(f'Original NP9 {np9}')

np8[1] = 33

print(f'Changed NP8 {np8}')
print(f'Changed NP9 {np9}')

#so diffrence between copy and view is , view is still connected to original when we changed the only original array.
'''

#copy
np9 = np8.copy()
print(f'Original NP9 {np8}')
print(f'Original NP10 {np9}')

np8[1] = 33

print(f'Changed NP8 {np8}')
print(f'Changed NP9 {np9}')

# so the copy function only copies the original and not connected to orginal array when changed.

[1 2 3 4 5 6 7 8 9]
Original NP9 [1 2 3 4 5 6 7 8 9]
Original NP10 [1 2 3 4 5 6 7 8 9]
Changed NP8 [ 1 33  3  4  5  6  7  8  9]
Changed NP9 [1 2 3 4 5 6 7 8 9]


In [13]:
#Shape and Reshape Numpy
np10 = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
'''print(np10)
print(np10.shape)

np11 = np.array([[1,2,3,4,5],[5,6,7,8,9]])
print(np11.shape)
# 2 rows and 5 elements in each
'''
#reshaping 2D
np12 = np10.reshape(3,4)
#(3,4 means 3 columns with 4 elements in each column)
print(np12)
print(np12.shape)

#reshaping 3D
np13 = np10.reshape(2,3,2)
print(np13)
print(np13.shape)
# 2 arrays with each containing 3 arrays with 2 elements 

#flatten to 1D
np14 = np10.reshape(-1)
print(np14)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
(3, 4)
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
(2, 3, 2)
[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [23]:
#iterating through numpy arrays

'''
np15 = np.array([1,2,3,4,5,6,7,8,9,10])
print(np15)
for x in np15:
    print(x)

#2D array 
np16 = np.array([[1,2,3,4,5],[6,7,8,9,10]])
for x in np16:
    print(x)
    
#to get access to inside elements 
    for y in x:
        print(y)
'''      
#3D array
np17 = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]]) 
'''for x in np17:
    print(x)
    for y in x:
        for z in y:
            print(z)
     '''       
#use np.nditer() - to loop in 3d arrays
for x in np.nditer(np17):
    print(x)

1
2
3
4
5
6
7
8
9
10
11
12


In [31]:
#sorting numpy arrays it is not changing the original but only sorting a copy of the array
np18 = np.array([6,7,5,3,9,1,2,0])
print(np.sort(np18))

#sorting alphabetical elements
np19 = np.array(['john','tina','reena','sattu'])
print(np.sort(np19))

#booleans T/F - False=0 ,True=1
np20 = np.array([True,False,True,False])
print(np.sort(np20))

#2D
np21 = np.array([[4,6,3,7],[3,9,7,1]])
print(np.sort(np21))

#3D
np22 = np.array([[[3,4,2,1]],[[66,42,74,12]]])
print(np.sort(np22))
np23 =np.shape(np22)
print(np23)

[0 1 2 3 5 6 7 9]
['john' 'reena' 'sattu' 'tina']
[False False  True  True]
[[3 4 6 7]
 [1 3 7 9]]
[[[ 1  2  3  4]]

 [[12 42 66 74]]]
(2, 1, 4)


In [44]:
#searching numpy arrays - np.where()
np24 = np.array([1,2,3,4,5,6,7,8,9,10,2,4,2,6])
x = np.where(np24 == 2)
print(x)
print(x[0])
print(np24[x[0]])

#return the even items - returns the index of the item
y =np.where(np24 % 2 == 0)
print(y[0])

#return the odd items - returns the index of he item
y = np.where(np24 % 2 == 1)
print(y[0])
z= np.where(np24 == 7)
print(z[0])

(array([ 1, 10, 12], dtype=int64),)
[ 1 10 12]
[2 2 2]
[ 1  3  5  7  9 10 11 12 13]
[0 2 4 6 8]
[6]


In [53]:
#filtering numpy arrays with boolean index
np25 = np.array([1,2,3,4,5,6,7,8,9,10])
print(np25)
x = [True,False,False,False,False,False,False,False,False,True]
print(np25[x])

#creating a filtering list
filtered = []
for thing in np25:
    if thing % 2 == 0:
        filtered.append(True)
    else:
        filtered.append(False)
print(filtered)
print(np25[filtered])

for greater in np25:
    if thing > 7:
        filtered.append(True)
    else:
        filtered.append(False)
print(filtered)

#Shorthand
filtered = np25 % 2 == 0
print(np25[filtered])

[ 1  2  3  4  5  6  7  8  9 10]
[ 1 10]
[False, True, False, True, False, True, False, True, False, True]
[ 2  4  6  8 10]
[False, True, False, True, False, True, False, True, False, True, True, True, True, True, True, True, True, True, True, True]
[ 2  4  6  8 10]
